name: Build HTML5 Export

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Setup Godot
        uses: firebelley/godot-export@v4.0
        with:
          godot-version: "4"
          export-preset: "HTML5"
          cache: true

      - name: Export HTML5
        uses: firebelley/godot-export@v4.0
        with:
          godot-version: "4"
          export-preset: "HTML5"
          output-path: "build/html5/"
